rmdir "F:\InternalTraining\CleanCode\BeforeMaybePattern\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\BeforeMaybePattern\obj" /S /Q
rmdir "F:\InternalTraining\CleanCode\BeforeNullObjectPattern\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\BeforeNullObjectPattern\obj" /S /Q
rmdir "F:\InternalTraining\CleanCode\Casting\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\Casting\obj" /S /Q
rmdir "F:\InternalTraining\CleanCode\CommandPattern\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\CommandPattern\obj" /S /Q
rmdir "F:\InternalTraining\CleanCode\Composition\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\Composition\obj" /S /Q
rmdir "F:\InternalTraining\CleanCode\DefaultVirtualParameters\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\DefaultVirtualParameters\obj" /S /Q
rmdir "F:\InternalTraining\CleanCode\DemeterLaw\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\DemeterLaw\obj" /S /Q
rmdir "F:\InternalTraining\CleanCode\Exceptions\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\Exceptions\obj" /S /Q
rmdir "F:\InternalTraining\CleanCode\Inheritance\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\Inheritance\obj" /S /Q
rmdir "F:\InternalTraining\CleanCode\LargeIfElseVSSwitchCase\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\LargeIfElseVSSwitchCase\obj" /S /Q
rmdir "F:\InternalTraining\CleanCode\Liste\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\Liste\obj" /S /Q
rmdir "F:\InternalTraining\CleanCode\Logging\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\Logging\obj" /S /Q
rmdir "F:\InternalTraining\CleanCode\LooseCoupling\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\LooseCoupling\obj" /S /Q
rmdir "F:\InternalTraining\CleanCode\MaybePattern\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\MaybePattern\obj" /S /Q
rmdir "F:\InternalTraining\CleanCode\NullObjectPatternDone\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\NullObjectPatternDone\obj" /S /Q
rmdir "F:\InternalTraining\CleanCode\OptimalUseOfCollections\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\OptimalUseOfCollections\obj" /S /Q
rmdir "F:\InternalTraining\CleanCode\StringOperations\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\StringOperations\obj" /S /Q
rmdir "F:\InternalTraining\CleanCode\TellDontAsk\bin" /S /Q
rmdir "F:\InternalTraining\CleanCode\TellDontAsk\obj" /S /Q
